### ISSUE TITLE
Module not found: Error: Can't resolve 'ngx-take-until-destroy'

### ISSUE THREAD

**Issue by shezadkhan137** [Nas3nmann/ngx-deep-linking#3]
After running `npm i @jdrks/ngx-deep-linking` on an Angular 12 project, I get the following error:

```
./node_modules/@jdrks/ngx-deep-linking/fesm2015/jdrks-ngx-deep-linking.js:6:0-56 - Error: Module not found: Error: Can't resolve 'ngx-take-until-destroy' in '{path}/node_modules/@jdrks/ngx-deep-linking/fesm2015'
```

It seems that [take-until-destroy](https://www.npmjs.com/package/ngx-take-until-destroy) is deprecated and should be replaced with [until-destroy](https://www.npmjs.com/package/@ngneat/until-destroy)

**Comment by Nas3nmann** [comment]
Hi @shezadkhan137 ,
thanks for trying out my library. 

`ngx-take-until-destroy` is a "peer-dependency" of this library. That means you have to install it in your project yourself. Npm should also have pointed this out to you in the install logs.

Regarding the deprecation of `ngx-take-until-destroy`: I wanted to ensure downward compatibility for Angular9 with this, but as I build the whole library on Angular 12 this was a failed attempt.
In future I will use Angular 9 in the library so it can easily be used with older version of Angular too. Also I will most likely remove `ngx-take-until-destroy` completely to have no further dependencies.
