### ISSUE TITLE
Add default for parameters

### ISSUE THREAD

**Issue by wertzui** [Nas3nmann/ngx-deep-linking#4]
Plase add a `default` property to `DeepLinkingPathParam` and `DeepLinkingQueryParam`.

I have a generic list component, which lists resources and serves as a kind of entry point.
Every element has a link to an edit page.
I want to configure that link in my routes without the need to create a wrapper component.

The list component takes
```
@Input()
public editLink: string;
```

In my routes I want to write
```
export const AppRoutes: DeepLinkingRoute[] = [
  {
    path: 'list',
    component: DeepLinkingWrapperComponent,
    wrappedComponent: ListViewComponent,
    deepLinking: {
      params: [
        { name: 'editLink', type: 'string', default '/edit' }
      ]
    }
  },
  {
    path: 'customlist',
    component: DeepLinkingWrapperComponent,
    wrappedComponent: ListViewComponent,
    deepLinking: {
      params: [
        { name: 'editLink', type: 'string', default: ' /customedit'}
      ]
    }
  }
  // more routes here
];
```

**Comment by wertzui** [comment]
Sorry for not being able to provide an example, as I'm quite busy at the moment.
As a workaround, I added a route(query) parameter and every link will supply the same value for that parameter.
That way I still have the parameter in the URL, but it works for now ;)

I will get back to this, once I have some more time.

**Comment by Nas3nmann** [comment]
@wertzui I will close this for now. Let me know once you have a clear requirement
