### ISSUE TITLE
Update dependencies to Angular 13

### ISSUE THREAD

**Issue by wertzui** [Nas3nmann/ngx-deep-linking#5]
Please update the dependencies from Angular 12 to Angular 13, as this breaks the restoring of npm packages when using Angular 13.

```
npm ERR! Found: @angular/common@13.2.5
npm ERR! node_modules/@angular/common
npm ERR!   dev @angular/common@"^13.2.5" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^12.1.1" from @jdrks/ngx-deep-linking@1.0.5
npm ERR! node_modules/@jdrks/ngx-deep-linking
npm ERR!   dev @jdrks/ngx-deep-linking@"^1.0.5" from the root project
```

**Comment by wertzui** [comment]
You might also need to migrate from https://www.npmjs.com/package/ngx-take-until-destroy to https://www.npmjs.com/package/@ngneat/until-destroy

**Comment by Nas3nmann** [comment]
Maybe it would be good to completely get rid of "ngx-take-until-destroy" and then set the required angular version to "9 - 13" for backward compatibility.
I will have a look into that in the next days.

**Comment by Nas3nmann** [comment]
@wertzui just released v1.0.6 which should be compatible with Angular 8-13. I also removed the dependency to ngx-take-until-destroy.
Would love to hear if it's working properly in your Angular 13 project.

**Comment by wertzui** [comment]
Thanks!
I'm not sure if I will be able to test it during the weekend but will do it definitely on Monday.

**Comment by wertzui** [comment]
I just tried it and I'm now getting errors about `rxjs`
Looks as if Angular wants a higher version than your library allows.

```
npm ERR!   dev rxjs@"^7.4.0" from the root project
npm ERR!   peer rxjs@"^6.5.3 || ^7.4.0" from @angular/cdk@13.2.5
npm ERR!   node_modules/@angular/cdk
npm ERR!     dev @angular/cdk@"^13.2.5" from the root project
npm ERR!     peer @angular/cdk@"13.2.5" from @jdrks/ngx-deep-linking@1.0.6
npm ERR!     node_modules/@jdrks/ngx-deep-linking
npm ERR!       dev @jdrks/ngx-deep-linking@"^1.0.6" from the root project
npm ERR!   3 more (@angular/common, @angular/core, @angular/router)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer rxjs@"~6.6.0" from @jdrks/ngx-deep-linking@1.0.6
npm ERR! node_modules/@jdrks/ngx-deep-linking
npm ERR!   dev @jdrks/ngx-deep-linking@"^1.0.6" from the root project
```

**Comment by Nas3nmann** [comment]
Hm... the peer dependencies are actually only:
`  "peerDependencies": {
    "@angular/common": ">= 8 < 14",
    "@angular/core": ">= 8 < 14",
    "@angular/router": ">= 8 < 14"
  }, `
I had my demo projects updated to Angular 13.2.5 too and they work fine with both yarn and npm.
I n both scenarios i have rxjs 6.6.7 installed.
Doe you have rxjs 7.x explicitly set in your package.json?

**Comment by Nas3nmann** [comment]
Great, thanks for the feedback.

**Comment by wertzui** [comment]
Sorry, but I'm still having a problem with dependcies.
Today I wanted to upgrade another project and ran again into problems with `rxjs`.

Then I compared the `package.json` from v1.0.6 from npm and Github.
On Github it states
```
  "peerDependencies": {
    "@angular/common": ">= 8 < 14",
    "@angular/core": ">= 8 < 14",
    "@angular/router": ">= 8 < 14"
  },
```

But on npm (after doing an `npm install @jdrks/ngx-deep-linking --force` in an empty folder it states
```
  "peerDependencies": {
    "@angular/common": ">= 8 < 14",
    "@angular/core": ">= 8 < 14",
    "@angular/router": ">= 8 < 14",
    "rxjs": "~6.6.0",
    "@angular/cdk": "13.2.5",
    "@angular/platform-browser-dynamic": "13.2.5"
  },
```

Could it be that you have uploaded the version 1.0.6 to npm, before you cleaned up the dependencies and pushed it to Github?

**Comment by wertzui** [comment]
Create an empty folder and run `npm install @jdrks/ngx-deep-linking --force`
Then inspect the `package.json` in the node_modules folder.

**Comment by wertzui** [comment]
Looks good now, thanks.
